sudo: required

language: ruby

services:
  - docker

env:
  - TARGET_CONTAINER_ID=container-docker-arch

script:
  - docker build -t tmp ./dockerfile/docker-arch
  - docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it tmp /bin/bash /mkimage-arch-jp.sh

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push $DOCKER_TEARM/docker-arch;
        docker build -t base ./dockerfile/archlinux;
        docker build -t min ./dockerfile/archlinux-min;
        docker build -t yaourt ./dockerfile/archlinux-yaourt;
        docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it base /bin/bash /mkimage-arch-jp.sh;
        docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it min /bin/bash /mkimage-arch-jp.sh;
        travis_retry docker run -v /var/run/docker.sock:/var/run/docker.sock --privileged -it yaourt /bin/bash /mkimage-arch-jp.sh;
        docker push $DOCKER_TEARM/archlinux;
        docker push $DOCKER_TEARM/archlinux-min;
        docker push $DOCKER_TEARM/archlinux-yaourt;
        export text=`docker images`;
  fi

